NewsProject/NewsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path("accounts/", include("allauth.urls")),
    path('', include('newsapp.urls')),
    path('posts/', include('newsapp.urls')),
]

NewsProject/newsapp/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('news/', NewsList.as_view(), name='news_list'),
    path('article/', ArticleList.as_view(), name='article_list'),
    path('<int:pk>', PostDetails.as_view(), name='post_detail'),
    path('news/<int:pk>', PostDetails.as_view(), name='post_detail'),
    path('article/<int:pk>', PostDetails.as_view(), name='post_detail'),
    path('news/create/', CreateNews.as_view(), name='news_create'),
    path('news/<int:pk>/update/', UpdateNews.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', DeleteNews.as_view(), name='news_delete'),
    path('article/create/', CreateArticle.as_view(), name='article_create'),
    path('article/<int:pk>/update/', UpdateArticle.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', DeleteArticle.as_view(), name='article_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('create/', ChoiceCreate.as_view(), name='choice'),
]

NewsProject/newsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

POSITION = [
    ('AR','Article'),
    ('NW','News')
]


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    rating_author = models.IntegerField(default=0)

    def update_rating(self):
        post_rate = self.post_set.aggregate(a = Sum('rating'))['a'] #так как метод возвращает словарь решил взять значение таким способом
        if post_rate == None:
            post_rate = 0                #если у автора нет постов метод возвращает None и возникает ошибка. Добовляем костыль.
        comm_rate = self.authorUser.comment_set.aggregate(b = Sum('rating'))['b']
        if comm_rate == None:
            comm_rate = 0

        self.rating_author = post_rate*3 + comm_rate
        self.save()

    def __str__(self):
        return self.authorUser.username


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    article = 'AR'
    news = 'NW'

    postAuthor = models.ForeignKey(Author, on_delete=models.CASCADE)
    postType = models.CharField(max_length=2, choices=POSITION, default=article)
    time_in = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField(default='Контент')
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:123]+'...'

    def __str__(self):
        return f'{self.title.title()}: {self.text[:20]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post.title} | {self.category.name}'



class Comment(models.Model):
    post_comment = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    time_in = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

NewsProject/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Статья</h1>
        <hr>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
{% endblock content %}

NewsProject/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
    <hr>
        <form action="" method="post">
            {% csrf_token %}
            <p>Удаляем "{{ object.name }}"?</p>
            <input type="submit" value="Delete" />
    </form>
{% endblock content %}

NewsProject/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Статья</h1>
        <hr>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
{% endblock content %}

NewsProject/templates/articles.html
{% extends 'flatpages/default.html' %}

{% load censor %}
{% load custom_tag %}

{% block title %}
Articles
{% endblock title %}


{% block content %}
    <h1>ALl articles</h1>
    <h3>Articles were published: {{ news|length }}</h3>

    <form action="" method="get">
       {{ filter.form.as_p }}
       <input type="submit" value="Найти" />
    </form>

    <hr>
        {% if news %}
            <table>
                <tr>
                    <td>Заголовок</td>
                    <td>Дата публикации</td>
                    <td>Содержание</td>
                </tr>
                {% for post in news %}
                    <tr>
                        <td><a href = '{{ post.id }}'>{{ post.title|cenz }}</a></td>
                        <td>{{ post.time_in|date:'M d Y' }}</td>
                        <td>{{ post.text|truncatewords:20|cenz }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <h2>Новостей нет!</h2>
        {% endif %}
        {% if page_obj.has_previous %}
            <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {{ page_obj.number }}


        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
{% endblock content %}

NewsProject/templates/choice.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Добавить</h1>
    <a href='/article/create'>Добавить статью</a>
    <a href='/news/create'>Добавить новость</a>
{% endblock content %}

NewsProject/templates/news.html
{% extends 'flatpages/default.html' %}

{% load censor %}
{% load custom_tag %}

{% block title %}
News
{% endblock title %}


{% block content %}
    <h1>All news</h1>
    <h3>News were published: {{ news|length }}</h3>
    <p align="left">
    <form action="" method="get">
       {{ filter.form.as_table }}
       <input type="submit" value="Найти" />
    </form>
    </p>
    <hr>
        {% if news %}
            <table>
                <tr>
                    <td>Заголовок</td>
                    <td>Дата публикации</td>
                    <td>Содержание</td>
                </tr>
                {% for post in news %}
                    <tr>
                        <td><a href = '{{ post.id }}'>{{ post.title|cenz }}</a></td>
                        <td>{{ post.time_in|date:'M d Y' }}</td>
                        <td>{{ post.text|truncatewords:20|cenz }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <h2>Новостей нет!</h2>
        {% endif %}
        {% if page_obj.has_previous %}
            <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {{ page_obj.number }}


        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
{% endblock content %}

NewsProject/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Новость</h1>
        <hr>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
{% endblock content %}

NewsProject/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
    <hr>
        <form action="" method="post">
            {% csrf_token %}
            <p>Удаляем "{{ object.name }}"?</p>
            <input type="submit" value="Delete" />
    </form>
{% endblock content %}

NewsProject/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Новость</h1>
        <hr>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
{% endblock content %}

NewsProject/templates/post.html
{% extends 'flatpages/default.html' %}
{% load censor %}
{% block title %}
Post
{% endblock title %}


{% block content %}
<h1>{{ post.title|cenz }}</h1>
<h3>{{ post.time_in|date:'M d Y' }}</h3>
<hr>
    {{ post.text|cenz }}
{% endblock content %}

NewsProject/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load censor %}
{% load custom_tag %}

{% block title %}
News
{% endblock title %}


{% block content %}
    <h1>Все посты</h1>
    <h3>Опубликовано постов: {{ news|length }}</h3>

    <form action="" method="get">
        <p>
        <label for="id_title__icontains">Title contains:</label>
        <input type="text" name="title__icontains" id="id_title__icontains" wfd-id="id0">

        </p>
        <p>
        <label for="id_categories">Categories:</label>
        <select name="categories" id="id_categories" multiple size="4">
            {% for cat in filter.form.categories %}
            {{cat}}
            {% endfor %}
        </select>


        </p>


        <p>
        <label for="id_add_after">Time in is greater than:</label>
        <input type="datetime-local" name="add_after" id="id_add_after" wfd-id="id1">
        </p>
        <input type="submit" value="Найти" />
    </form>

    <hr>
        {% if news %}
            <table>
                <tr>
                    <td>Заголовок</td>
                    <td>Дата публикации</td>
                    <td>Содержание</td>
                </tr>
                {% for post in news %}
                    <tr>
                        <td><a href = '{{ post.id }}'>{{ post.title|cenz }}</a></td>
                        <td>{{ post.time_in|date:'M d Y' }}</td>
                        <td>{{ post.text|truncatewords:20|cenz }}</td>

                        <td>
                        {% if perms.newsapp.change_post %}
                            {% if post.postType == 'NW' %}
                                <a href="{% url 'news_update' pk=post.id %}">Изменить</a>
                            {% endif %}
                            {% if post.postType == 'AR' %}
                                <a href="{% url 'article_update' pk=post.id %}">Изменить</a>
                            {% endif %}
                        {% endif %}
                        {% if perms.newsapp.delete_post %}
                            {% if post.postType == 'NW' %}
                                <a href="{% url 'news_delete' post.id %}">Удалить</a>
                            {% endif %}
                            {% if post.postType == 'AR' %}
                                <a href="{% url 'article_delete' post.id %}">Удалить</a>
                            {% endif %}
                        {% endif %}
                    </td>

                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <h2>Новостей нет!</h2>
        {% endif %}
        {% if page_obj.has_previous %}
            <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {{ page_obj.number }}


        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
{% endblock content %}